### ISSUE TITLE
nai chalra 

### ISSUE THREAD

**Issue by Anshs-12** [jdeepak1218/html-myportfolio#1]
ahf l alif kjadshgfiadhsfi gsad gblfsb lglakjsbg g bjfdhadshfia boiuers bfadsbfcasd[ifjalsn dcfkasdbfk jladsg fkjadnslkfnas dkj;lbnsfkv;lnadsd;lkcn asohdf kiadbsv ckldsbiyutgfarsfnv;lads

**Comment by jdeepak1218** [comment]
okay sir
